step1
ShivanshSinghnnovative/polling-system pull request #1
Opened 2023-10-04 13:49 UTC by ShivanshSinghnnovative

2023-10-10 07:19 UTC, PiyushInnotech commented on src/composables/loginsignup.js
> +                localStorage.setItem('user', JSON.stringify(userData));
use userDetails

2023-10-10 07:21 UTC, PiyushInnotech commented on src/composables/loginsignup.js
> +                const userData = {
get userDetails from response.

2023-10-10 07:24 UTC, PiyushInnotech commented on src/composables/loginsignup.js
> +    store.dispatch('fetchRoles').then(() => {
use onMounted and computed property

2023-10-10 07:26 UTC, PiyushInnotech commented on src/composables/loginsignup.js
> +                    } finally {
remove finally

2023-10-10 07:27 UTC, PiyushInnotech commented on src/composables/loginsignup.js
> +    const isSubmitted = ref(false)
change name to something like openSuccesModal

2023-10-10 07:28 UTC, PiyushInnotech commented on src/pages/loginPage.vue
> +
too much gap and also check format

2023-10-11 06:41 UTC, yuvrajInno requested changes

2023-10-11 06:41 UTC, yuvrajInno commented on src/composables/loginsignup.js
> +    const rolesData = computed(() => {
there are 2 roles data can't we use 1 @ShivanshSinghnnovative

2023-10-11 06:56 UTC, merged