add-update
ShivanshSinghnnovative/polling-system pull request #3
Opened 2023-10-14 13:15 UTC by ShivanshSinghnnovative

2023-10-20 06:17 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +      window.location.reload();
change this function

2023-10-20 06:18 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +  const openSinglePoll = async (id) => {
change the name

2023-10-20 06:20 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +export const openSingleApi = () => {
change name for function

2023-10-20 06:23 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +          createdBy: 1,
why static

2023-10-20 06:28 UTC, PiyushInnotech commented on src/pages/updateTitle.vue
> +        console.log(singlePoll.value)
remove console

2023-10-20 12:16 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +          title: updatedText,
also send trimed text

2023-10-20 13:56 UTC, meanstack9716 requested changes

2023-10-20 13:56 UTC, meanstack9716 commented on src/composables/pollingDetails.js
> +    if(!pollsData.value.length){
code not formatted @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/composables/pollingDetails.js
> +  const pollsData = computed(() => {
if you are not doing anything with pollsData variable, you can simply put it into the return object @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/composables/pollingDetails.js
> +  })
same for this computed property @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/composables/pollingDetails.js
> +  const singlePoll = computed(() => {
same for this computed property @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/pages/pollingPage.vue
>      </button>
what is pollingPage? is this for single Poll or is this For Poll list page? Can you choose a better name @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/pages/pollingPage.vue
> +  router.push(`/updatetitle/${id}`)
page for an update title? No, it will go to update Poll page, from there user can update anything in the poll @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/pages/singlePoll.vue
> +  <div class="h-screen m-auto flex justify-center" v-if="isLoading">
create a loader component for it, and use it every where @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/pages/singlePoll.vue
> +      <div class="text-2xl p-4 font-bold   m-auto  bg-gray-400 "   >{{singlePoll.title}}</div> </div>
why too many spaces in class names @ShivanshSinghnnovative

2023-10-20 13:56 UTC, meanstack9716 commented on src/pages/updateTitle.vue
> +    <span class=" text-7xl flex justify-center " v-if="isLoading">
this page not needed, this all functionality will be inside the poll update page @ShivanshSinghnnovative

2023-10-25 13:40 UTC, PiyushInnotech commented on src/components/loaderIcon.vue
> +    <font-awesome-icon icon="fa-solid fa-spinner" spin />
center the loader

2023-10-26 10:44 UTC, PiyushInnotech commented on src/components/logoutModal.vue
> +const closeMenu = () => {
useEmit function

2023-10-26 10:45 UTC, PiyushInnotech commented on src/components/navbarMenu.vue
> +const routesArr = [
create single config file and get routesArr from there

2023-10-26 10:57 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +    option.value = options;
remove

2023-10-26 10:59 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +      if (option.value) {
use else if

2023-10-27 05:55 UTC, PiyushInnotech commented on src/components/deletePopModal.vue
> +          Are you sure to delete
change the message

2023-10-27 06:11 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +      if (newPoll.options.length > 2) {
remove these condition

2023-10-27 06:14 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +  const updateExistingPollOption = (options, index) => {
remove index

2023-10-27 06:15 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +  const addOptionInExistingPoll = async (newOption, id) => {
instead for id use pollId

2023-10-27 06:22 UTC, PiyushInnotech commented on src/composables/pollingDetails.js
> +  const updateExistingOption = async (options, optionId, id) => {
change to optiontitle

2023-10-27 06:24 UTC, PiyushInnotech commented on src/pages/createPoll.vue
> +if (id !== undefined && id !== null && id.trim() !== "") {
these is wrong

2023-10-27 06:26 UTC, PiyushInnotech commented on src/pages/pollListPage.vue
> +  router.push(`/updatetitle/${id}`)
change route to update poll

2023-10-27 06:27 UTC, PiyushInnotech commented on src/store/index.js
> +    updatePollTitleUi(state, payload) {
change change

2023-10-27 06:28 UTC, PiyushInnotech commented on src/store/index.js
> +        commit("deleteExistingPoll", id);
reverse these

2023-10-27 06:29 UTC, PiyushInnotech commented on src/store/index.js
> +      commit('updatePollTitleUi', { pollId, title })
same here

2023-10-27 07:04 UTC, meanstack9716 requested changes

2023-10-27 07:04 UTC, meanstack9716 commented on src/components/deletePopModal.vue
> +const emit = defineEmits({});
can you define your emits here @ShivanshSinghnnovative https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits

2023-10-27 07:04 UTC, meanstack9716 commented on src/components/logoutModal.vue
> +const emit = defineEmits({});
same here @ShivanshSinghnnovative

2023-10-27 07:04 UTC, meanstack9716 commented on src/components/navbarMenu.vue
> +    router.push(`${href}`)
why do you need `${}` syntax? @ShivanshSinghnnovative

2023-10-27 07:33 UTC, merged